### ISSUE TITLE
Allow pod annotation to modify tosi's extractto parameter

### ISSUE THREAD

**Issue by justnoise** [elotl/itzo#101]
We want to be able to enable and disable using an overlay root filesystem for containers. According to @ldx: with our current overlay rootfs setup, "the kernel ends up caching the base rootfs in the page cache, taking up memory a lot of itzo's memory" we want to experiment with NOT doing that to ease memory usage on each itzo cell.

Itzo uses https://github.com/elotl/tosi to extract container images.  We want to be able to have the pod annotation `pod.elotl.co/use-image-overlay-rootfs` to choose between calling tosi with the `-mount` vs `-extractto` arguments.  If `pod.elotl.co/use-image-overlay-rootfs` is true-ish, (use `strconv.ParseBool()` to convert the string value) or missing, use `-mount` (currently the hardcoded value) in the tosi command line argument, and if that annotation is falsish, call tosi with `-extractto` argument.  You'll need to ask @ldx whether we should be using the same directory argument for `-mount` and `-extract`.

To make this work:

1. Itzo has its own definition of `pkg/api.PodParameters`.  Kip issue https://github.com/elotl/kip/issues/178 updated `PodParameters` to pass pod annotations to Itzo.  The itzo definition of that structure needs to be updated as well because we are lazy CopyPaste people.
2. Pod updates from kip end up in the `podParams` variable in `PodController.runUpdateLoop()`
3. Suggested by @ldx: copy the annotations into a map of annotations in the `PodController`.
4. When pulling the image in the PodController, pull out the `pod.elotl.co/use-image-overlay-rootfs` annotation, convert it to a bool pass it through to tosi
5. Run tosi with the correct arguments (either `-mount` or `-extractto`).

Be aware that issue https://github.com/elotl/itzo/issues/76 is in progress and will updated `PodController.SyncPodUnits` as well.

**Comment by ldx** [comment]
Good recap, thanks!

As for 3), I think we could pull out _all_ `pod.elotl.co` annotations from `podParams`, put them in a map, and then save them in the `PodController` struct, so later on it'll be easier to pass in other pod-specific configuration parameters. Thoughts?

**Comment by justnoise** [comment]
> As for 3), I think we could pull out _all_ `pod.elotl.co` annotations from `podParams`, put them in a map, and then save them in the `PodController` struct, so later on it'll be easier to pass in other pod-specific configuration parameters. Thoughts?

@ldx: I like that a lot better!  Updating the issue with that.
