### ISSUE TITLE
Create Anka VM template that is able to build kickstarter OSS app

### ISSUE THREAD

**Issue by ldx** [elotl/itzo#131]

**Comment by hidalgopl** [comment]
Tips from Nathan:
>Nathan Pierce:us:  7:34 PM
Yep, I do
7:34
Or have recently anyway
7:36
You'll need to use https://github.com/Carthage/Carthage/blob/master/Documentation/Xcode12Workaround.md to work around an Xcode 12 bug
GitHubGitHub
Carthage/Carthage
A simple, decentralized dependency manager for Cocoa - Carthage/Carthage
Paweł Bojanowski  7:38 PM
that's great. do you think there is a possibility that you can share vm template with us? if that's not feasible, I'd really appreciate any tips like the one above:)
Nathan Pierce:us:  7:39 PM
At the moment there is no public repository for templates. You can easily create with using the anka create CLI or even the getting-started script: https://github.com/veertuinc/getting-started#create-vm-templatebash
GitHubGitHub
veertuinc/getting-started
Anka getting started scripts and resources. Contribute to veertuinc/getting-started development by creating an account on GitHub.
7:40
That script is an example of how you can automate the creation process for templates, layer by layer, using tags.
7:40
I would recommend you use it to create the base template you clone from to create your Xcode template
7:40
That way, the xcode template can be re-created by just cloning from the original template and not have to install macOS over again

**Comment by hidalgopl** [comment]
Possible workflow:
- boot mac1.metal instance from the latest mac AMI that we're using.
- use aws ssm to log into the instance shell
- check if anka license is valid `sudo anka license validate`
- if not, activate it
- use `c0847bc9-5d2d-4dbc-ba6a-240f7ff08032` as a base vm template
- run base vm template: `sudo anka start c0847bc9-5d2d-4dbc-ba6a-240f7ff08032`
- once it is running, you can exec commands in the vm and then use `sudo anka suspend` command to "save" your changes to the template

running VM commands looks like this: `sudo anka run c0847bc9-5d2d-4dbc-ba6a-240f7ff0803 brew install buildkite/buildkite/buildkite-agent`

Probably, you'll need to clone [kickstarter](https://github.com/elotl/ios-oss) into the VM to test if `make bootstrap` & `make test-all` commands work.
Once those two pass, we should suspend the vm to save a state and create AMI from the instance, so the vm template is persisted on host anka registry.
